/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.Logic.CusDic;
import Business.Logic.RecDic;
import Business.Models.Course;
import Business.Models.CourseRecord;
import Business.Models.VipCustomer;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import userinterface.MainJFrame;

/**
 *
 * @author 27246
 */
public class CourseRecordJPanel extends javax.swing.JPanel {

    JPanel container;
    List<Course> listCourse;
    List<CourseRecord> listCourseRecord;
    /**
     * Creates new form CourseRecordJPanel
     */
    public CourseRecordJPanel(JPanel container) {
        initComponents();
        this.container = container;
        LoadCourseData();
        LoadRecord();
    }
    
    public void paintComponent(Graphics g){
        int x = 0;
        int y = 0;
        ImageIcon icon = new ImageIcon("dalishi.jpg");
        //g.setColor(new Color(0,0,0,220));
        g.drawImage(icon.getImage(), x, y, getSize().width,getSize().height,this);
    }
    
    public void LoadCourseData(){
        listCourse = RecDic.QueryCourse("0");
        if(MainJFrame.userAccount.customer.Role.equals("CustomerWithTrainer")){
            VipCustomer vc = RecDic.GetVipCustomer(MainJFrame.userAccount.getUsername());
            if(vc==null) return;
            List<Course> list = RecDic.QueryPrivateCourse(vc.PrivateTrainerUserName);
            if(list!=null) {
                for (int i = 0; i < list.size(); i++) {
                    listCourse.add(list.get(i));
                }
            }
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableCourse.getModel();
        String[] cols = new String[]{"Course Name","Date","Time","Trainer","Class Hour","Address"};
        String[][] rows= new String[listCourse.size()][6];
        for (int i = 0; i < listCourse.size(); i++) {
            rows[i][0] = listCourse.get(i).CourseName;
            rows[i][1] = listCourse.get(i).CourseDate;
            rows[i][2] = listCourse.get(i).CourseTime;
            rows[i][3] = listCourse.get(i).TrainerName;
            rows[i][4] = String.format("%d", listCourse.get(i).ClassHour);
            rows[i][5] = listCourse.get(i).Address;
        }
        
        tableModel.setDataVector(rows, cols);
    }
    public void LoadRecord(){
        listCourseRecord = CusDic.GetourseRecord(MainJFrame.userAccount.getUsername());
        String[] cols = new String[]{"ID","Course Name","Date","Time","Sign Time"};
        String[][] rows= new String[listCourseRecord.size()][5];
        for (int i = 0; i < listCourseRecord.size(); i++) {
            rows[i][0] = listCourseRecord.get(i).ID;
            rows[i][1] = listCourseRecord.get(i).CourseName;
            rows[i][2] = listCourseRecord.get(i).CourseDate;
            rows[i][3] = listCourseRecord.get(i).CourseTime;
            rows[i][4] = listCourseRecord.get(i).CheckTime;
        }
        DefaultTableModel tableModel = (DefaultTableModel)this.tableRecord.getModel();
        tableModel.setDataVector(rows, cols);
        TableColumn column = null;
        column = tableRecord.getColumnModel().getColumn(0);
        column.setWidth(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSignin = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRecord = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labInfo = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableCourse);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Course List:");

        btnSignin.setText("Sign in");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });

        tableRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableRecord);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Course Record:");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(740, 740, 740)
                                    .addComponent(btnSignin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
                                .addComponent(jScrollPane1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(labInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBack, btnDelete, btnSignin});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(352, Short.MAX_VALUE)
                        .addComponent(labInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSignin)))
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDelete)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnDelete, btnSignin});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
        int n = this.tableCourse.getSelectedRow();
        if(n<0) return;
        Course c = this.listCourse.get(n);
        CourseRecord cr =new CourseRecord();
        cr.Address = c.Address;
        cr.ClassHour = c.ClassHour;
        cr.CourseDate = c.CourseDate;
        cr.CourseID = c.CourseID;
        cr.CourseName = c.CourseName;
        cr.CourseTime = c.CourseTime;
        cr.IsPrivate = c.IsPrivate;
        cr.OrgID = c.OrgID;
        cr.TrainerName = c.TrainerName;
        cr.TrainerUserName = c.TrainerUserName;
        cr.username = MainJFrame.userAccount.customer.username;
        cr.realname = MainJFrame.userAccount.customer.realname;
        boolean res = CusDic.AddCourseRecord(cr);
        if(res==false){
            this.labInfo.setText("has record");
        }
        else{
            LoadRecord();
        }
    }//GEN-LAST:event_btnSigninActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);  
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int n = this.tableRecord.getSelectedRow();
        if(n<0) return;
        CusDic.DeleteCourseRecord(this.tableRecord.getValueAt(n, 0).toString());
        //RecDic.DeleteCourse(this.tableRecord.getValueAt(n, 0).toString());
        this.LoadRecord();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labInfo;
    private javax.swing.JTable tableCourse;
    private javax.swing.JTable tableRecord;
    // End of variables declaration//GEN-END:variables
}
