/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.MainJFrame;

/**
 *
 * @author 0
 */
public class CustomerManagementJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerManagementJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Enterprise restaurant;
    public CustomerManagementJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise restaurant) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.restaurant = restaurant;
        UserNamelbl.setText(userAccount.getUsername());
    }
    
    public void paintComponent(Graphics g){
        int x = 0;
        int y = 0;
        ImageIcon icon = new ImageIcon("pulati.jpg");
        //g.setColor(new Color(0,0,0,220));
        g.drawImage(icon.getImage(), x, y, getSize().width,getSize().height,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHealthInformation = new javax.swing.JButton();
        btnSign = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        UserNamelbl = new javax.swing.JLabel();

        btnHealthInformation.setText("Health information");
        btnHealthInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHealthInformationActionPerformed(evt);
            }
        });

        btnSign.setText("Sign in Course");
        btnSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Hello,");

        UserNamelbl.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        UserNamelbl.setText("<UserName>");
        UserNamelbl.setPreferredSize(new java.awt.Dimension(200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSign, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHealthInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(UserNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHealthInformation, btnSign});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserNamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnHealthInformation)
                .addGap(18, 18, 18)
                .addComponent(btnSign, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {UserNamelbl, jLabel2});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnHealthInformation, btnSign});

    }// </editor-fold>//GEN-END:initComponents

    private void btnHealthInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHealthInformationActionPerformed
        // TODO add your handling code here:
        if(userAccount.getRole().getType().equals("Customer")){
            CustomerWorkAreaJPanel customerWorkAreaJPanel = new CustomerWorkAreaJPanel(userProcessContainer, userAccount, restaurant);
            userProcessContainer.add("customerWorkAreaJPanel",customerWorkAreaJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        else{
            VIPCustomerWorkAreaJPanel vipCustomerWorkAreaJPanel = new VIPCustomerWorkAreaJPanel(userProcessContainer, userAccount,restaurant);
            userProcessContainer.add("vipCustomerWorkAreaJPanel",vipCustomerWorkAreaJPanel);
            CardLayout layout=(CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnHealthInformationActionPerformed

    private void btnSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignActionPerformed
        if (MainJFrame.userAccount.customer==null) {
            JOptionPane.showMessageDialog(null, "You have not input cunstomer info");
            return;
        }
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        userProcessContainer.add("workArea",new CourseRecordJPanel(this.userProcessContainer));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSignActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserNamelbl;
    private javax.swing.JButton btnHealthInformation;
    private javax.swing.JButton btnSign;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
