/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.trainer;

import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import userinterface.MainJFrame;

/**
 *
 * @author Administrator
 */
public class TrainerMainJPanel extends javax.swing.JPanel {

    JPanel container;
    /**
     * Creates new form TrainerMainJPanel
     */
    public TrainerMainJPanel(JPanel container) {
        initComponents();
        this.container = container;
        if(MainJFrame.userAccount.getRole().getType().equals("CommonTrainer")){
            this.btnSetCourse.setEnabled(false);
            this.btnViewCustomer.setEnabled(false);
        }
         if(MainJFrame.userAccount.getRole().getType().equals("PrivateTrainer")){
            this.btnViewCourse.setEnabled(false);  
        }  
    }
    
    public void paintComponent(Graphics g){
        int x = 0;
        int y = 0;
        ImageIcon icon = new ImageIcon("jiaolian1.jpg");
        //g.setColor(new Color(0,0,0,220));
        g.drawImage(icon.getImage(), x, y, getSize().width,getSize().height,this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSetCourse = new javax.swing.JButton();
        btnViewCourse = new javax.swing.JButton();
        btnViewRecord = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        btnSetCourse.setText("Set My Course");
        btnSetCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetCourseActionPerformed(evt);
            }
        });

        btnViewCourse.setText("View Common Course");
        btnViewCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCourseActionPerformed(evt);
            }
        });

        btnViewRecord.setText("View Course Record");
        btnViewRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRecordActionPerformed(evt);
            }
        });

        btnViewCustomer.setText("View My Customer");
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to trainer system!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewCourse)
                    .addComponent(jLabel1)
                    .addComponent(btnViewRecord)
                    .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnSetCourse, btnViewCourse, btnViewCustomer, btnViewRecord});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(btnViewCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnViewRecord)
                .addGap(20, 20, 20)
                .addComponent(btnViewCustomer)
                .addGap(20, 20, 20)
                .addComponent(btnSetCourse)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnSetCourse, btnViewCourse, btnViewCustomer, btnViewRecord});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSetCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCourseActionPerformed
         CardLayout layout=(CardLayout)container.getLayout();
         container.add("workArea",new SetMyCourseJPanel(this.container));
         layout.next(container);
    }//GEN-LAST:event_btnSetCourseActionPerformed

    private void btnViewCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCourseActionPerformed
         CardLayout layout=(CardLayout)container.getLayout();
         container.add("workArea",new ViewVipCourseJPanel(this.container));
         layout.next(container);
    }//GEN-LAST:event_btnViewCourseActionPerformed

    private void btnViewRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRecordActionPerformed
         CardLayout layout=(CardLayout)container.getLayout();
         container.add("workArea",new ViewCourseRecordJPanel(this.container));
         layout.next(container);        
    }//GEN-LAST:event_btnViewRecordActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed
         CardLayout layout=(CardLayout)container.getLayout();
         container.add("workArea",new ViewMyCustomerJPanel(this.container));
         layout.next(container);   
    }//GEN-LAST:event_btnViewCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSetCourse;
    private javax.swing.JButton btnViewCourse;
    private javax.swing.JButton btnViewCustomer;
    private javax.swing.JButton btnViewRecord;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
