/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Restaurant;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.restaurant.Food;
import java.awt.CardLayout;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.CustomerRole.ShowFitnessListJPanel;
import userinterface.DoctorRole.FitnessListJPanel;

/**
 *
 * @author 0
 */
public class DietitianWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DietitianWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem system;
    public DietitianWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        
        populateCustomer();
        populateFood();
    }
    
    public void paintComponent(Graphics g){
        int x = 0;
        int y = 0;
        ImageIcon icon = new ImageIcon("dalishi.jpg");
        //g.setColor(new Color(0,0,0,220));
        g.drawImage(icon.getImage(), x, y, getSize().width,getSize().height,this);
    }

    public void populateFood(){
        DefaultTableModel dtm = (DefaultTableModel) tabFood.getModel();
        dtm.setRowCount(0);
        for(Food f: enterprise.getMenu().getFoodList()){
            Object[] row = new Object[2];
            row[0] = f;         
            row[1] = f.getPrice();           
            dtm.addRow(row);
        }
    }
    
    public void populateCustomer(){
        DefaultTableModel dtm = (DefaultTableModel) tabCustomer.getModel();
        dtm.setRowCount(0);
        
        for(Organization org : findCusEnterprise().getOrganizationDirectory().getOrganizationList()){
            for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                if(ua.getRole().getType().equals("CustomerWithTrainer")){
                    Object row[] = new Object[7];
                    row[0] = ua.getEmployee().getId();
                    row[1] = ua;
                    row[2] = ua.getEmployee().getAge();
                    row[3] = ua.getEmployee().getGender();
                    row[4] = ua.getEmployee().getBirthday();
                    row[5] = ua.getEmployee().getPhone();
                    row[6] = ua.getEmployee().getAddress();
                    dtm.addRow(row);
                }
            }
        }
    }
    
    public Enterprise findCusEnterprise(){
        Enterprise cusEnterprise = null;
        for(Network network : system.getNetworkList()){
            for(Enterprise e:network.getEnterpriseDirectory().getEnterpriseList()){
                if(e.getName().equals(enterprise.getName())){
                    for(Enterprise findEnterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                        if(findEnterprise.getEnterpriseType()==Enterprise.EnterpriseType.Population){
                            cusEnterprise = findEnterprise;
                        }
                    }
                }
            }
        }
        return cusEnterprise;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabCustomer = new javax.swing.JTable();
        btnFresh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnCreateDietList = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabFood = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateDietList = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Make healthy diet plan");

        tabCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Age", "Gender", "Birthday", "Phone", "Address"
            }
        ));
        jScrollPane1.setViewportView(tabCustomer);

        btnFresh.setText("fresh");
        btnFresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFreshActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Search by ID:");

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnView.setText("view report");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCreateDietList.setText("add diet list");
        btnCreateDietList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDietListActionPerformed(evt);
            }
        });

        tabFood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "food name", "price"
            }
        ));
        jScrollPane2.setViewportView(tabFood);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Present menu");

        btnUpdateDietList.setText("update diet list");
        btnUpdateDietList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDietListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnFresh, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnCreateDietList, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                        .addComponent(btnUpdateDietList))))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(jLabel1)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCreateDietList, btnFresh, btnUpdateDietList, btnView, txtSearch});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(btnFresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateDietList)
                    .addComponent(btnCreateDietList))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreateDietList, btnFresh, btnUpdateDietList, btnView, txtSearch});

    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText();
        if(id.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter an ID!","Warning",JOptionPane.WARNING_MESSAGE);
                return;
        }
        UserAccount ua = null;
         for(Organization org : findCusEnterprise().getOrganizationDirectory().getOrganizationList()){
                ua = org.getUserAccountDirectory().findUserAccount(Integer.parseInt(id));
                if(ua != null) break;
            }
            if(ua != null){
                ShowFitnessListJPanel showFitnessListJPanel = new ShowFitnessListJPanel(userProcessContainer, ua);
                userProcessContainer.add("showFitnessListJPanel",showFitnessListJPanel);
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else
                JOptionPane.showMessageDialog(null, "This id is not existing!","Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnFreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFreshActionPerformed
        // TODO add your handling code here:
        populateCustomer();
    }//GEN-LAST:event_btnFreshActionPerformed

    private void btnCreateDietListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDietListActionPerformed
        // TODO add your handling code here:
        
        String id = txtSearch.getText();
        if(id.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter an ID!","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
        UserAccount ua = null;
         for(Organization org : findCusEnterprise().getOrganizationDirectory().getOrganizationList()){
                ua = org.getUserAccountDirectory().findUserAccount(Integer.parseInt(id));
                if(ua != null) break;
            }
            if(ua != null){
                CreateDietListJPanel createDietListJPanel = new CreateDietListJPanel(userProcessContainer,ua,enterprise);
                userProcessContainer.add("createDietListJPanel",createDietListJPanel);
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else
                JOptionPane.showMessageDialog(null, "This id is not existing!","Warning",JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btnCreateDietListActionPerformed

    private void btnUpdateDietListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDietListActionPerformed
        // TODO add your handling code here:
        String id = txtSearch.getText();
        if(id.equals("")){
                JOptionPane.showMessageDialog(null, "Please enter an ID!","Warning",JOptionPane.WARNING_MESSAGE);
                return;
        }
        UserAccount ua = null;
         for(Organization org : findCusEnterprise().getOrganizationDirectory().getOrganizationList()){
                ua = org.getUserAccountDirectory().findUserAccount(Integer.parseInt(id));
                if(ua != null) break;
            }
            if(ua != null){
                ViewDietListJPanel viewDietListJPanel = new ViewDietListJPanel(userProcessContainer,ua,enterprise);
                userProcessContainer.add("viewDietListJPanel",viewDietListJPanel);
                CardLayout layout=(CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            else
                JOptionPane.showMessageDialog(null, "This id is not existing!","Warning",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnUpdateDietListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDietList;
    private javax.swing.JButton btnFresh;
    private javax.swing.JButton btnUpdateDietList;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabCustomer;
    private javax.swing.JTable tabFood;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
