/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Reception;

import Business.Logic.RecDic;
import Business.Logic.UserDic;
import Business.Models.Course;
import Business.Models.User;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Common.DB;
import java.awt.CardLayout;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import userinterface.MainJFrame;

/**
 *
 * @author Administrator
 */
public class CourseJPanel extends javax.swing.JPanel {

    JPanel container;
    private String CourseID = null;
    List<Course> listCourse;
    /**
     * Creates new form CourseJPanel
     */
    public CourseJPanel(JPanel container) {
        initComponents();
        this.container = container;
        this.txtClassHour.setText("50");
        LoadTrainerData();
        LoadCourseData();
    }
    
    public void paintComponent(Graphics g){
        int x = 0;
        int y = 0;
        ImageIcon icon = new ImageIcon("dalishi.jpg");
        //g.setColor(new Color(0,0,0,220));
        g.drawImage(icon.getImage(), x, y, getSize().width,getSize().height,this);
    }
    
    public void LoadCourseData(){

        listCourse = RecDic.QueryCourse(MainJFrame.userAccount.Enterprise.getName(),"0");
        DefaultTableModel tableModel = (DefaultTableModel)this.tableCourse.getModel();
        
        String[] cols = new String[]{"Course Name","Date","Time","Trainer","Class Hour","Address"};
        String[][] rows= new String[listCourse.size()][6];
        for (int i = 0; i < listCourse.size(); i++) {
            rows[i][0] = listCourse.get(i).CourseName;
            rows[i][1] = listCourse.get(i).CourseDate;
            rows[i][2] = listCourse.get(i).CourseTime;
            rows[i][3] = listCourse.get(i).TrainerName;
            rows[i][4] = String.valueOf(listCourse.get(i).ClassHour);
            rows[i][5] = listCourse.get(i).Address;
        }
        tableModel.setDataVector(rows, cols);
        TableColumn column = null;
        column = tableCourse.getColumnModel().getColumn(5);
        column.setPreferredWidth(150);
        
    }
    public void LoadTrainerData(){
        for (int i = 0; i < MainJFrame.userAccount.Enterprise.getOrganizationDirectory().getOrganizationList().size(); i++) {
            Organization o = MainJFrame.userAccount.Enterprise.getOrganizationDirectory().getOrganizationList().get(i);
            ArrayList<UserAccount> list = o.getUserAccountDirectory().getUserAccountList();
            for (int j = 0; j < list.size(); j++) {
               
                UserAccount u = list.get(j);
                 System.out.println(u.getRole().getType());
                if(u.getRole().getType().equals("CommonTrainer")){
                    this.comboTrainer.addItem(u.getUsername());
                }
            }
        }
       
//        List<User> list = UserDic.QueryUseyByTypes(new String[]{"4"});
//        for (int i = 0; i < list.size(); i++) {
//            this.comboTrainer.addItem(list.get(i));
//        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboTrainer = new javax.swing.JComboBox<String>();
        jLabel5 = new javax.swing.JLabel();
        txtClassHour = new javax.swing.JFormattedTextField();
        btnSave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCourse = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        comboCourseName = new javax.swing.JComboBox<>();
        comboBoxCourseDate = new javax.swing.JComboBox<>();
        comboTime = new javax.swing.JComboBox<>();
        comboBoxAddress = new javax.swing.JComboBox<>();
        btnDelete = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Course Name:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Course Date:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Time:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Trainer:");

        comboTrainer.setModel(new javax.swing.DefaultComboBoxModel<String>());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Class Hour(min):");

        txtClassHour.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtClassHour.setText("50");
        txtClassHour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClassHourActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        tableCourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableCourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCourseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCourse);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Address：");

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        comboCourseName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belly Dance", "Aerobic Dance", "Step", "Pilates", "SPINNING", "Flow Yoga", "Resist-a-ball", "Latin dance", "Ballet", "Yin yoga", "Burning Fat Exercise" }));

        comboBoxCourseDate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MON", "TUES", "WEN", "THUR", "FRI", "SAT", "SUN", " " }));

        comboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10:00-10:50", "16:00-16:50", "18:00-18:50", "19:00-19:50", " " }));

        comboBoxAddress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Building 12  Room 101", "Building 12  Room 102", "Building 12  Room 103", "Building 12  Room 104", "Building 12  Room 105", "Building 12  Room 106" }));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Course Management System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(comboCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboTrainer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClassHour, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxCourseDate, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addGap(165, 165, 165)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnReset)
                            .addGap(18, 18, 18)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 831, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {comboBoxAddress, comboBoxCourseDate, comboCourseName, comboTime, comboTrainer, txtClassHour});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDelete, btnReset, btnSave});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack)
                    .addComponent(jLabel6))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxCourseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtClassHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(comboBoxAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTrainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset)
                    .addComponent(btnSave)
                    .addComponent(btnDelete))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBack, btnDelete, btnReset, btnSave, comboBoxAddress, comboBoxCourseDate, comboCourseName, comboTime, comboTrainer, jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, txtClassHour});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        Course c = new Course();
        c.CourseID = this.CourseID;
        c.CourseName = (String)this.comboCourseName.getSelectedItem();
        c.CourseDate = (String)this.comboBoxCourseDate.getSelectedItem();
        c.CourseTime = (String)this.comboTime.getSelectedItem();
        if(this.txtClassHour.getText().isEmpty())this.txtClassHour.setText("0");
        c.ClassHour = Integer.parseInt(this.txtClassHour.getText());
        c.Address = (String)this.comboBoxAddress.getSelectedItem();
        c.TrainerUserName = this.comboTrainer.getSelectedItem().toString();
        c.TrainerName = c.TrainerUserName;
        //c.TrainerUserName = trainer.username;
        c.OrgID = MainJFrame.userAccount.Enterprise.getName();
        
        List<Course> listCourse1;
        listCourse1 = RecDic.QueryCourse(MainJFrame.userAccount.Enterprise.getName(),"0");
        List<Course> listCourse2 = new ArrayList<Course>();
        List<Course> listCourse3 = new ArrayList<Course>();
        String date = comboBoxCourseDate.getSelectedItem().toString();
        String time = comboTime.getSelectedItem().toString();

        for(Course c1 : listCourse1){
            if(c1.CourseDate.equals(date)){
                listCourse2.add(c1);
            }
        }

        for(Course c2 : listCourse2){
            if(c2.CourseTime.equals(time)){
                JOptionPane.showMessageDialog(null, "Time conflict!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        String name = this.comboCourseName.getSelectedItem().toString();
        for(Course c3 : listCourse2){
            if(c3.CourseName.equals(name)){
                JOptionPane.showMessageDialog(null, "Course conflict!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        
        c.IsPrivate = "0";
        boolean res = RecDic.SaveCourse(c);
        if(res) {
            this.LoadCourseData();
            ReSet();
        }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void ReSet(){
        this.CourseID = null;
        this.comboCourseName.setSelectedItem("Belly Dance");
        this.comboBoxCourseDate.setSelectedItem("MON");
        this.comboTime.setSelectedItem("10:00-10:50");
        this.txtClassHour.setText("50");
        this.comboBoxAddress.setSelectedItem("Building 12  Room 101");
    }
    private void tableCourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCourseMouseClicked
        // TODO add your handling code here:
        int n = this.tableCourse.getSelectedRow();
        if(n<0) return;
        if(this.listCourse!=null){
            Course c = this.listCourse.get(n);
            this.CourseID = c.CourseID;
            this.comboCourseName.setSelectedItem(c.CourseName);
            this.comboBoxCourseDate.setSelectedItem(c.CourseDate);
            this.comboTime.setSelectedItem(c.CourseTime);
            this.txtClassHour.setText(String.format("%d", c.ClassHour));
            this.comboBoxAddress.setSelectedItem(c.Address);
           // this.txtAddress.setText(c.Address);
        }
    }//GEN-LAST:event_tableCourseMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        ReSet();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int n = this.tableCourse.getSelectedRow();
        if(n<0) return;
        RecDic.DeleteCourse(this.tableCourse.getValueAt(n, 0).toString());
        this.LoadCourseData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtClassHourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClassHourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClassHourActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> comboBoxAddress;
    private javax.swing.JComboBox<String> comboBoxCourseDate;
    private javax.swing.JComboBox<String> comboCourseName;
    private javax.swing.JComboBox<String> comboTime;
    private javax.swing.JComboBox<String> comboTrainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableCourse;
    private javax.swing.JFormattedTextField txtClassHour;
    // End of variables declaration//GEN-END:variables
}
